# Generated by Django 5.1.1 on 2024-10-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_created_reviewflags_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date_of_experience',
        ),
    ]
