# Generated by Django 5.1.1 on 2024-11-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_review_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.CharField(default='46TJGKMvJX4W34tNtUg8cE', max_length=27, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='TJcSdDVeY3mAMLPWnfYwgT', max_length=27, primary_key=True, serialize=False, unique=True),
        ),
    ]
