# Generated by Django 5.1.1 on 2024-10-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='industry',
            new_name='category',
        ),
        migrations.AddField(
            model_name='company',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='subcategory',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='job_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='work_email',
            field=models.EmailField(default='', max_length=200),
        ),
    ]
