# Generated by Django 5.1.1 on 2024-10-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_rename_industry_company_category_company_is_claimed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, unique=True),
        ),
    ]
