# Generated by Django 5.1.1 on 2024-11-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default='5Dsgs8vL5Bo3GsxqaTPW6G', max_length=27, primary_key=True, serialize=False, unique=True),
        ),
    ]
